language: ruby
rvm:
  - 2.3
  - 2.6
before_install:
  - gem update --system
  - gem install bundler -v '< 2'
  - gem uninstall bundler -v '>= 2'
script: bundle exec rake
notifications:
  email: false
